import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RootFooter from "@/components/layout/rootFooter";
import RootHeader from "@/components/layout/rootHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RootHeader/>
       <div
              style={{ minHeight: "calc(100vh)" }}
              className="pt-[130px] md:pt-[95px] bg-[#FCFCFC] "
            >
              {children}
            </div>
        <RootFooter/>
      </body>
    </html>
  );
}
